require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'
platform :ios, '13.0'

target 'ipostop' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  # Pods for ipostop
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  
end

installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if [
          "React-cxxreact",
          "React-utils",
          "React-NativeModulesApple",
          "React-jserrorhandler",
          "React-ImageManager",
          "React-graphics",
          "React-Fabric",
          "ReactCommon",
          "RNReanimated",
          "React-Codegen",
          "React-RCTNetwork",
          "React-RCTVibration",
          "React-RCTSettings",
          "React-RCTLinking",
          "React-RCTAnimation",
          "React-RCTImage",
          "React-RCTBlob",
          "React-CoreModules",
          "React-RCTAppDelegate"
        ].any? { |t| t == target.name }
          config.build_settings["HEADER_SEARCH_PATHS"] ||= "$(inherited) "
          config.build_settings["HEADER_SEARCH_PATHS"] << "${PODS_ROOT}/../../node_modules/react-native/ReactCommon "
          config.build_settings["HEADER_SEARCH_PATHS"] << "${PODS_ROOT}/../../node_modules/react-native/ReactCommon/react/nativemodule/core/platform/ios/ "
          config.build_settings["HEADER_SEARCH_PATHS"] << "${PODS_ROOT}/../../node_modules/react-native/ReactCommon/react/nativemodule/core/ "
        end
   end
end
